services:
  inbucket:
    image: inbucket/inbucket:3.0.3
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
    volumes:
      - inbucket:/storage

volumes:
  inbucket:
    driver: local
